### ISSUE TITLE
Volume Mapping and documentation

### ISSUE THREAD

**Issue by xrebelox** [Luctia/ezarr#14]
I'm having a little bit of trouble understanding the documentation when it comes to media management and the qbittorrent management.

The documentation mentions the following points:
- Root folder: /data/media/ and then tv, movies or music depending on service
- In qBittorrent, after connecting it to the -arr services, you can indicate it should move torrents in certain categories to certain directories, like torrents in the radarr category to /data/torrents/movies. You should do this.

However, when trying to add the root folders I can't seem to find the respective subfolders {tv,movies,music,books} as well as it doesn't allow me to add the data folder for some reason.

The same applies when configuring the folder on qbitorrent for a given category, for example, radarr gives me an error saying that it can't find /data/torrents/movies.

Am I supposed to change the volumes in the `docker-compose.yml`? I'm a bit lost here

**Comment by xrebelox** [comment]
I'm dumb sorry

**Comment by furey** [comment]
Hi @xrebelox,

Can you explain how you solved the issue please? 😊 

Cheers!

**Comment by jen-arr-yay-tuh** [comment]
i had this exact issue

i was using Ubuntu, and using `docker` from `snap`, which was borked

i uninstalled the `snap` version of `docker`, and installed `docker` officially via https://docs.docker.com/engine/install/ubuntu/

this worked
