### ISSUE TITLE
Cannot set root path in sonarr and radarr due to permissons

### ISSUE THREAD

**Issue by zdbeer** [Luctia/ezarr#20]
Hi there. 

Amazing piece of software you have here. This will probably turn into the go-to way to setup a servarr in the future due to its ease of use, especially due to the folder structures. 

After using CLI and trying to set the root path on Sonarr for example, it cannot access the default `data/media/tv` path. The Sonarr log says ` -- Path: Folder is not writable by user abc`
``
Looking at the permissions (in my case `/home/username/servarr/data/media`) by running ls -ltr, 

I get 
```
drwxrwxr-x 2 root root 4096 Jan 25 13:39 tv  

drwxrwxr-x 2 root root 4096 Jan 25 13:39 movies
```
Manually changing permissions of `/home/username/servarr/data/media` using `sudo chown -R 13001 /home/username/servarr/data/media/tv` seems to fix the issue.

Is this expected behavior?

**Comment by zdbeer** [comment]
I can give an exact list of actions on a clean ubuntu install if it will help

**Comment by Luctia** [comment]
Pull request above should fix this issue. Thanks for letting me know!
