### ISSUE TITLE
Setup a support system like a Discord

### ISSUE THREAD

**Issue by fryfrog** [Luctia/ezarr#42]
It would also be great if you could setup a support system, like a Discord server or something.

Or maybe start hanging out on the sonarr/radarr discord and helping people that use ezarr?

**Comment by Luctia** [comment]
I could join discords like that, but I don't have it open often so it wouldn't help much. The GitHub discussions page (perhaps in combination with the issues page) satisfies the need for support in my opinion. I get a notification every time something is posted there and try to reply as quickly as I can.
