### ISSUE TITLE
SABnzbd having issues saving config

### ISSUE THREAD

**Issue by cosmicsalad** [Luctia/ezarr#57]
Everything else is working correctly, but for some reason I've been running into this permissions issue only with SABnzbd when installed ezarr. 
` Cannot create backup file for /config/sabnzbd.ini.bak`

when checking permission it's showing the ini and ini.bak in a different group id than the rest:
```
carousels@plexbox:/media/plexmedia/config $ ls -ltr sabnzbd-config
total 640
drwxrwxr-x 2 carousels carousels 131072 Sep 11 16:22 logs
drwxrwxr-x 4 carousels carousels 131072 Sep 11 16:22 Downloads
-rwxrwxr-x 1 carousels carousels   8231 Sep 24 17:35 sabnzbd.ini
drwxrwxr-x 2 carousels carousels 131072 Sep 24 18:10 admin
-rwxrwxr-x 1 carousels carousels   8231 Sep 24 18:26 sabnzbd.ini.bak
```

When trying to manually set permissions with setup.sh I get this for most config files:
`chown: changing ownership of '/media/plexmedia/config/sabnzbd-config/sabnzbd.ini': Operation not permitted`

I setup ezarr using the CLI so I'm confused as to how SAB's config wouldn't be able to save since I haven't changed anything after install.

**Comment by Luctia** [comment]
Hi, can you provide your docker compose file?

**Comment by cosmicsalad** [comment]
Sorry, it was actually an issue with my drive being formatted as exfat. Kept receiving chown errors on directories/files since I now learned exfat isn't capable of using chown. So reformatted as ext4 and now it's all working as expected.
