### ISSUE TITLE
Can't get default timezone on archlinux

### ISSUE THREAD

**Issue by estevanbs** [Luctia/ezarr#60]
The script thows an error when I try to use the system's configured timezone on archlinux.

1. Run the script on archlinux.
2. Press enter when the timezone question is printed (`Please enter your timezone (like "Europe/Amsterdam") or press enter to use your system's configured timezone:`).
3. It will stop the configuration process returning this error.
```
Traceback (most recent call last):
  File "/home/estevan/ezarr/main.py", line 117, in <module>
    timezone = open("/etc/timezone", "r").readline()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Expected behavior**
The expected behavior is the script getting the system timezone from where it exists. The file `/etc/timezone` doesn't exists on archlinux systems.

**Additional context**
I can get the timezone with the command `timedatectl status`, but I'm not sure if this will work with Ubuntu based os.
```
$ timedatectl status
[...]
Time zone: America/Sao_Paulo (-03, -0300)
[...]
```

**Comment by Luctia** [comment]
The README of this project indicates support for Ubuntu, and the project in general is aimed at people who don't have much experience with Linux/Docker, who don't overlap very much, in my opinion, with Arch users. Someone can make a PR for this, but it'll have to still work on Ubuntu and it doesn't have much priority for me at the moment.
