### ISSUE TITLE
SABnzbd  Not working

### ISSUE THREAD

**Issue by awptechnologies** [Luctia/ezarr#66]
I believe SABnzbd is not working because my host has ipv6 disabled and therefore it is failing to listen on port 8080 inside container. Do you have any idea how to disable ipv6 in SABnzbd? i have checked there website and forums and cant find anything anywhere. Other linuxserver docker containers i use there is a default folder that contains the nginx config and i can delete the ipv6 stuff but with the SABnzbd container i don't see that folder populated. i see the .ini file for SABnzbd in config but i don't see an obvious option to disable ipv6.

**Comment by Luctia** [comment]
This sounds like an issue with SABnzbd rather than with Ezarr. I don't use SABnzbd myself so I'm not sure how this part of it works, but you could consider opening a question on StackExchange or on discussions on this repository. Either way, I don't think this fits in issues.

**Comment by awptechnologies** [comment]
I figured it out thank you though. The linuxserver image has an environment variable to disable ipv6

HAS_IPV6=false
