### ISSUE TITLE
Feature Request: Bridge Network

### ISSUE THREAD

**Issue by stevietv** [Luctia/ezarr#8]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Add a bridge network for the stack and assign all containers to that bridge network. That way all containers can use docker DNS and refer to each other by container name

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Luctia** [comment]
Referring to each other by container name already works, as a matter of fact, it's the only way to link Servarr apps and qBittorrent, for example. Is that what you mean by this? The setting isn't explicitly stated in the `docker-compose.yml` file because it's the default.
